manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/drorchen
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: dracula-test
      import: app/west.yml
  self:
    path: config