manifest:
  remotes:
    - name: germain-gadel
      url-base: https://github.com/germain-gadel
    - name: zmkfirmware
      url-base: https://github.com/bullwinkle3000
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: pmw3610-aml
      import: app/west.yml
  self:
    path: config